const productsArray = [
  {
    id: 0,
    name: "Футболка Стиль-1",
    cost: 15,
    description: "Футболка с логотипом ПГЭК",
    parameters: "Размер: XL",
    photoUrl: "img/product1.jpg",
    photoUrl1: "img/test2.jpg",
    photoUrl_second: "img/test3.jpg",
    isRecommended: true,
  },
  {
    id: 1,
    name: "Футболка Стиль-2",
    cost: 15,
    description: "Футболка с логотипом ПГЭК",
    parameters: "Размер: L",
    photoUrl: "img/product2.jpg",
    photoUrl1: "img/test2.jpg",
    photoUrl_second: "img/test3.jpg",
    isRecommended: true,
  },
  {
    id: 2,
    name: "Толстовка Стиль-1",
    cost: 25,
    description: "Толстовка с логотипом ПГЭК",
    parameters: "Размер: XL",
    photoUrl: "img/product3.jpg",
    photoUrl1: "img/test2.jpg",
    photoUrl_second: "img/test3.jpg",
    isRecommended: true,
  },
  {
    id: 3,
    name: "Куртка Стиль-1",
    cost: 30,
    description: "Куртка с логотипом ПГЭК",
    parameters: "Размер: XL",
    photoUrl: "img/product4.jpg",
    photoUrl1: "img/test2.jpg",
    photoUrl_second: "img/test3.jpg",
    isRecommended: true,
  },
  {
    id: 4,
    name: "Рюкзак Стиль-1",
    cost: 25,
    description: "Рюкзак с логотипом ПГЭК",
    parameters: "Цвет: Синий",
    photoUrl: "img/product5.jpg",
    photoUrl1: "img/test2.jpg",
    photoUrl_second: "img/test3.jpg",
    isFavorites: true,
  },
  {
    id: 5,
    name: "Рюкзак Стиль-2",
    cost: 25,
    description: "Рюкзак с логотипом ПГЭК",
    parameters: "Цвет: Белый",
    photoUrl: "img/product6.jpg",
    photoUrl1: "img/test2.jpg",
    photoUrl_second: "img/test3.jpg",
    isFavorites: true,
  },
  {
    id: 6,
    name: "Мешок Стиль-1",
    cost: 17,
    description: "Рюкзак с логотипом ПГЭК",
    parameters: "Цвет: Синий",
    photoUrl: "img/product7.jpg",
    photoUrl1: "img/test2.jpg",
    photoUrl_second: "img/test3.jpg",
    isFavorites: true,
  },
];

localStorage.setItem("products", JSON.stringify(productsArray));
